username="4"
password="4"
domain="soroush.ir"
ejabberd_cluster_nodes="192.168.95.180:5222"
zookeeper_cluster_nodes="192.168.95.171:2181"
zookeeper_namespace="/watch"
rest_api_port=":8080"
client_ping_interval=2
