rest_api_port=":8080"

[zookeeper]
cluster_nodes="192.168.95.171:2181"
namespace="/watch"

[mysql]
address="127.0.0.1:3306"
username="root"
password="123"
db="test"

[redis]
cluster_nodes="127.0.0.1:6379"
password=""
db=0
PingInterval=2

[ejabberd]
cluster_nodes="192.168.95.180:5222"
default_cluster="A"

[client]
username="4"
password="4"
domain="soroush.ir"
ping_interval=2
