rest_api_port=":8080"
debug_port=":6060"
input_buffer=100
output_buffer=100
logic_process_number=2

[monitoring]
buffer_report_duration=1

[log]
log_level="debug"
format="text"

[kafka-consumer]
zookeeper="127.0.0.1:2181/"
topics="test-topic"
group_name="announcerz"
buffer=1000

[mysql]
address="127.0.0.1:3306"
username="root"
password="123"
db="testDB"
pagination_length=100
max_ideal_conn=50
max_open_conn=50

[redis]
cluster_nodes="127.0.0.1:6379"
password=""
db=0
set_prefix="192.168."
check_interval=100
gmet_buffer=100

[ejabberd]
cluster_nodes="127.0.0.1:8889"
rate_limit=10 #msg/sec
send_retry=6
each_node_conn_num=1

#[client]
#username="admin"
#password="password1234"
#domain="example.de"
#ping_interval=2 #Second
#resource="announcer"

[component]
name="announcer"
secret="announcer"
domain="soroush.ir"
ping_interval=110
max_conn_check_retry=10000
conn_req_check_interval=10

[kafka-producer]
brokers="127.0.0.1:9092"
topics="test-topic"
flush_frequency=1
max_retry=5